---
env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - prettier
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - jest
  - react
  - react-hooks
  - prettier
  - "@typescript-eslint"
settings:
  react:
    version: detect
rules:
  max-len:
    - error
    - code: 120
      ignoreUrls: true
      ignoreComments: false
      ignoreRegExpLiterals: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
  quotes:
    - error
    - double
  prettier/prettier:
    - error
#  import/prefer-default-export: 0
