---
env:
  browser: true
  es2021: true
  jest/globals
      ignoreStrings: true
      ignoreTemplateLiterals: true
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
  quotes:
    - error
    - double
  prettier/prettier:
    - error
#  import/prefer-default-export: 0
